import { gradients, palette, radii, shadows, spacing, surfaces, typography } from './tokens';

export const colors = {
  background: palette.casinoMidnight,
  surface: surfaces.elevatedCard,
  surfaceMuted: palette.casinoPurpleMuted,
  primary: palette.neonViolet,
  secondary: palette.neonCyan,
  accent: palette.neonPink,
  felt: palette.felt,
  feltDark: palette.feltDark,
  feltDeep: palette.feltDeep,
  gold: palette.gold,
  success: palette.success,
  text: palette.text,
  textSoft: palette.textSoft,
  mutedText: palette.textMuted,
  border: palette.border,
  danger: palette.danger,
  action: palette.action,
  muted: palette.muted,
  glowCyan: palette.glowCyan,
  glowGold: palette.glowGold,
  glowDanger: palette.glowDanger,
  cardFace: palette.cardFace,
  cardBorder: palette.cardBorder,
  white: palette.white,
  black: palette.black,
  modalBackdrop: surfaces.modalBackdrop,
  destructivePanel: surfaces.destructivePanel,
  goldTint: surfaces.goldTint,
  successTint: surfaces.successTint,
  cyanTint: surfaces.cyanTint,
  casinoNightGradient: gradients.casinoNight,
  gradients,
  palette,
  radii,
  shadows,
  spacing,
  surfaces,
  typography,
  roles: {
    backdrop: surfaces.modalBackdrop,
    cardBlackSuit: palette.cardBlack,
    cardClub: palette.cardBlack,
    cardDiamond: palette.cardDiamond,
    cardHeart: palette.cardHeart,
    cardRedSuit: palette.cardRed,
    chipLabelOnGold: palette.textOnGold,
    destructivePanel: surfaces.destructivePanel,
    elevatedCard: surfaces.elevatedCard,
    feltTable: palette.felt,
    glassPanel: surfaces.glassPanel,
    goldAccent: palette.gold,
    inputField: surfaces.inputField,
    navigationBar: surfaces.navigationBar,
    successAccent: palette.success,
  },
} as const;
