import type { ChatRoom } from '../types/chatRooms';

// TODO: Replace this isolated mock data with backend-powered chat room discovery,
// realtime social messages, active-player presence, table setup, and invite state.
export const chatRooms: ChatRoom[] = [
  {
    id: 'the-rail',
    title: 'The Rail',
    description: 'Coordinate casual free-play tables and find open seats with regulars.',
    topic: 'Casual table planning',
    unreadCount: 3,
    activePlayerCount: 18,
    lastMessagePreview: 'Maya has two open seats for a low-pressure warmup table.',
    players: [
      {
        id: 'maya',
        displayName: 'Maya Chen',
        handle: '@maya',
        avatarInitials: 'MC',
        status: 'available',
        chipStackLabel: '48K play chips',
        isHost: true,
      },
      {
        id: 'jax',
        displayName: 'Jax Rivers',
        handle: '@riverjax',
        avatarInitials: 'JR',
        status: 'inTable',
        chipStackLabel: '31K play chips',
      },
      {
        id: 'noor',
        displayName: 'Noor Patel',
        handle: '@noor',
        avatarInitials: 'NP',
        status: 'available',
        chipStackLabel: '22K play chips',
      },
    ],
    messages: [
      {
        id: 'rail-system-1',
        roomId: 'the-rail',
        authorId: 'system',
        authorName: 'House Bot',
        body: 'Welcome to The Rail. Keep gameplay talk friendly and launch tables only when everyone opts in.',
        createdAt: '2026-06-02T17:05:00.000Z',
        tone: 'system',
      },
      {
        id: 'rail-message-1',
        roomId: 'the-rail',
        authorId: 'maya',
        authorName: 'Maya Chen',
        body: 'Opening a four-seat free-play table in ten. Who wants a warmup orbit?',
        createdAt: '2026-06-02T17:11:00.000Z',
        tone: 'player',
      },
      {
        id: 'rail-message-2',
        roomId: 'the-rail',
        authorId: 'noor',
        authorName: 'Noor Patel',
        body: 'I can join after the current hand. Please hold one seat.',
        createdAt: '2026-06-02T17:13:00.000Z',
        tone: 'player',
      },
    ],
    tableConfig: {
      gameLabel: 'Texas Hold’em',
      stakesLabel: 'Free-play / 5K buy-in',
      maxSeats: 4,
      seatsOpen: 2,
      tableCode: 'RAIL42',
      isPrivate: false,
    },
    inviteState: {
      roomId: 'the-rail',
      pendingInvites: ['@riverjax'],
      shareLink: 'houseofpoker://chat-rooms/the-rail',
      suggestedHandles: ['@noor', '@acekat', '@buttonbob'],
    },
  },
  {
    id: '357-study-group',
    title: '3-5-7 Study Group',
    description: 'Talk through 3-5-7 strategy and training-table etiquette before jumping in.',
    topic: '3-5-7 hostest drills',
    unreadCount: 0,
    activePlayerCount: 11,
    lastMessagePreview: 'Theo posted a reminder about comparing three-card and seven-card lines.',
    players: [
      {
        id: 'theo',
        displayName: 'Theo Grant',
        handle: '@theo',
        avatarInitials: 'TG',
        status: 'available',
        chipStackLabel: '39K play chips',
        isHost: true,
      },
      {
        id: 'lina',
        displayName: 'Lina Ortiz',
        handle: '@lina',
        avatarInitials: 'LO',
        status: 'away',
        chipStackLabel: '27K play chips',
      },
      {
        id: 'sam',
        displayName: 'Sam Walker',
        handle: '@sam',
        avatarInitials: 'SW',
        status: 'available',
        chipStackLabel: '16K play chips',
      },
    ],
    messages: [
      {
        id: 'study-system-1',
        roomId: '357-study-group',
        authorId: 'system',
        authorName: 'House Bot',
        body: 'Strategy rooms are social spaces. Start a table when the group is ready to practice.',
        createdAt: '2026-06-02T16:52:00.000Z',
        tone: 'system',
      },
      {
        id: 'study-message-1',
        roomId: '357-study-group',
        authorId: 'theo',
        authorName: 'Theo Grant',
        body: 'Tonight’s drill: keep notes on how your three-card hand changes the seven-card plan.',
        createdAt: '2026-06-02T16:58:00.000Z',
        tone: 'player',
      },
      {
        id: 'study-message-2',
        roomId: '357-study-group',
        authorId: 'sam',
        authorName: 'Sam Walker',
        body: 'I’m in. A private training table works best so we can pause between rounds.',
        createdAt: '2026-06-02T17:02:00.000Z',
        tone: 'player',
      },
    ],
    tableConfig: {
      gameLabel: '3-5-7 Showdown',
      stakesLabel: 'Free-play training',
      maxSeats: 3,
      seatsOpen: 1,
      tableCode: '357LAB',
      isPrivate: true,
    },
    inviteState: {
      roomId: '357-study-group',
      pendingInvites: ['@lina'],
      shareLink: 'houseofpoker://chat-rooms/357-study-group',
      suggestedHandles: ['@sam', '@mathshark', '@linecheck'],
    },
  },
  {
    id: 'social-lounge',
    title: 'Social Lounge',
    description: 'Share player introductions and schedule friend-table sessions.',
    topic: 'Introductions and friend tables',
    unreadCount: 6,
    activePlayerCount: 24,
    lastMessagePreview: 'Ari is building a beginner-friendly table for new friends.',
    players: [
      {
        id: 'ari',
        displayName: 'Ari Stone',
        handle: '@ari',
        avatarInitials: 'AS',
        status: 'available',
        chipStackLabel: '52K play chips',
        isHost: true,
      },
      {
        id: 'kim',
        displayName: 'Kim Brooks',
        handle: '@kim',
        avatarInitials: 'KB',
        status: 'available',
        chipStackLabel: '19K play chips',
      },
      {
        id: 'dev',
        displayName: 'Dev Morgan',
        handle: '@dev',
        avatarInitials: 'DM',
        status: 'inTable',
        chipStackLabel: '44K play chips',
      },
    ],
    messages: [
      {
        id: 'lounge-system-1',
        roomId: 'social-lounge',
        authorId: 'system',
        authorName: 'House Bot',
        body: 'This room is for social planning and introductions. Gameplay chat stays inside active tables.',
        createdAt: '2026-06-02T15:42:00.000Z',
        tone: 'system',
      },
      {
        id: 'lounge-message-1',
        roomId: 'social-lounge',
        authorId: 'ari',
        authorName: 'Ari Stone',
        body: 'New player table forming at the top of the hour. Friendly pacing, no rush.',
        createdAt: '2026-06-02T15:47:00.000Z',
        tone: 'player',
      },
      {
        id: 'lounge-message-2',
        roomId: 'social-lounge',
        authorId: 'kim',
        authorName: 'Kim Brooks',
        body: 'Perfect, I’ll invite two friends who just finished onboarding.',
        createdAt: '2026-06-02T15:50:00.000Z',
        tone: 'player',
      },
    ],
    tableConfig: {
      gameLabel: 'Texas Hold’em',
      stakesLabel: 'Free-play beginner table',
      maxSeats: 6,
      seatsOpen: 3,
      tableCode: 'LOUNGE',
      isPrivate: true,
    },
    inviteState: {
      roomId: 'social-lounge',
      pendingInvites: ['@kim', '@dev'],
      shareLink: 'houseofpoker://chat-rooms/social-lounge',
      suggestedHandles: ['@firstdeal', '@friendlybet', '@ari'],
    },
  },
];
