export const routes = {
  Welcome: 'Welcome',
  Login: 'Login',
  Registration: 'Registration',
  Home: 'Home',
  ChatRooms: 'ChatRooms',
  ChatRoomDetail: 'ChatRoomDetail',
  Profile: 'Profile',
  UserProfile: 'UserProfile',
  Friends: 'Friends',
  Feed: 'Feed',
  MyFeed: 'MyFeed',
  PlayerDirectory: 'PlayerDirectory',
  Game: 'Game',
  Notifications: 'Notifications',
} as const;
