const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const Module = require('node:module'); const path = require('node:path'); const ts = require('typescript');
const { mockColors } = require('./mockTheme');
function find(node, predicate, matches = []) { if (!node || typeof node !== 'object') return matches; if (predicate(node)) matches.push(node); for (const child of Array.isArray(node.props?.children) ? node.props.children : [node.props?.children]) find(child, predicate, matches); return matches; }
function loadCard() {
  const state = [], refs = []; let cursor = 0, refCursor = 0;
  const react = { ...require('react'), useMemo: (factory) => factory(), useRef: (initial) => refs[refCursor++] ?? (refs[refCursor - 1] = { current: initial }), useState: (initial) => { const index = cursor++; if (!(index in state)) state[index] = initial; return [state[index], (value) => { state[index] = typeof value === 'function' ? value(state[index]) : value; }]; } };
  const rn = { ActivityIndicator: 'ActivityIndicator', Alert: { alert() {} }, Dimensions: { get: () => ({ width: 320, height: 640 }) }, Modal: 'Modal', Pressable: 'Pressable', StyleSheet: { absoluteFill: { position: 'absolute' }, create: (styles) => styles }, Text: 'Text', TextInput: 'TextInput', View: 'View' };
  const filename = path.resolve(__dirname, '../src/components/feed/FeedPostCard.tsx'); const output = ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { jsx: ts.JsxEmit.ReactJSX, module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText; const compiled = new Module(filename, module); compiled.filename = filename; compiled.paths = Module._nodeModulePaths(path.dirname(filename)); const original = compiled.require.bind(compiled); const mocks = { react, 'react-native': rn, '@expo/vector-icons': { MaterialCommunityIcons: 'Icon' }, '../../theme/colors': { colors: mockColors }, './FeedActionBar': { FeedActionBar: () => null }, './FeedPlayerHeader': { FeedPlayerHeader: () => null }, './FeedMediaGallery': { FeedMediaGallery: () => null } }; compiled.require = (request) => Object.hasOwn(mocks, request) ? mocks[request] : original(request); compiled._compile(output, filename);
  const noop = () => {}; const props = { currentUserId: 'owner', post: { id: 'post-2', authorUserId: 'owner', player: { id: 'owner' }, content: 'post', timestamp: '', media: [], supportersCount: 0, commentCount: 0, shareCount: 0, isPromoted: false }, onComment: noop, onDeleteComment: noop, onDeletePost: noop, onFetchComments: noop, onGiftClips: noop, onJoinTable: noop, onOpenProfile: noop, onPromote: noop, onShare: noop, onSupportChange: noop, onUpdateComment: noop, onUpdatePost: noop };
  return { render: () => { cursor = 0; refCursor = 0; return compiled.exports.FeedPostCard(props); } };
}
test("a post's More button anchors its actions menu below and right-aligned to that button", () => { const card = loadCard(); let tree = card.render(); const more = find(tree, (element) => element.props?.accessibilityLabel === 'More post actions')[0]; more.props.ref.current = { measureInWindow: (callback) => callback(250, 100, 38, 38) }; more.props.onPress(); tree = card.render(); const modal = find(tree, (element) => element.type === 'Modal')[0]; const menu = find(modal, (element) => Array.isArray(element.props?.style) && element.props.style[0]?.width === 180)[0]; assert.equal(modal.props.visible, true); assert.deepEqual(menu.props.style[1], { left: 108, top: 138 }); assert.notEqual(menu.props.style[0].alignItems, 'center'); });
